### PR TITLE
feat(glossary): Project glossary support 

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1101

api: https://github.com/zanata/zanata-api/pull/61
client: https://github.com/zanata/zanata-client/pull/127
server: https://github.com/zanata/zanata-server/pull/1285

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-common/30)

### CODE REVIEW

**Comment by huangp** [comment]
We stop doing batching?

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-common/30#-:-KR18dyfTSPlHlp17VFu:biblhul)*

**Comment by huangp** [comment]
:lgtm: -(Awaiting review)  +(On QA) 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-common/30#-:-KR1xf_iAh_FBA-1xeM3:b-66vna4)*

**Comment by huangp** [comment]
+Reviewed 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-common/30#-:-KR1xjmbNwmedYmwB9qN:bk26f37)*

**Comment by aeng** [comment]
I've moved the batching logic into zanata client. The idea was to use GlossaryFileUploadForm in the future for any file upload.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-common/30#-:-KR1xcU9nSUIhtp74A0q:b-lww0az)*

**Pull request merged**
