### PR TITLE
feat(glossary export): Glossary writer

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-153

https://github.com/zanata/zanata-api/pull/54
https://github.com/zanata/zanata-client/pull/117
https://github.com/zanata/zanata-server/pull/1190

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-common/27)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryCSVWriter.java, line 45 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-common/27#-KJYlVhO59Fl9_S3xKy_:-KJYlVhPI07QqZSC2tKE:-882069967) ([raw file](https://github.com/zanata/zanata-common/blob/f4345caf9575d55a8737be7d61ddb5d50c8675d7/zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryCSVWriter.java#L45)):*
> ```Java
>      * Last column (description)-  {@link GlossaryEntry#description}
>      * Between first and second last column - translations of <code>transLocales</code> from {@link GlossaryEntry#glossaryTerms}
>      */
> ```

The comment is exactly the same as below. Could just do a @see to reference to the other method. This will avoid us maintaining two copies of text

---

*[zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryCSVWriter.java, line 92 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-common/27#-KJYmQho2k33gL35I5uy:-KJYmQho2k33gL35I5uz:279314743) ([raw file](https://github.com/zanata/zanata-common/blob/f4345caf9575d55a8737be7d61ddb5d50c8675d7/zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryCSVWriter.java#L92)):*
> ```Java
>                 row.add(0, srcTerm != null ? srcTerm.getContent() : "");
> 
>                 int index = 1;
> ```

I don't think you need to use index here when adding to rowx. You are adding srcTerm.getContent() as first element. Then iterate over transLocales for translation terms. Then pos and description. There won't be any missing column in the process (from what I can see. Correct me if I am wrong)

---

*[zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryPoWriter.java, line 39 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-common/27#-KJYnWxvkhEZz4dFLulV:-KJYnWxvkhEZz4dFLulW:970492324) ([raw file](https://github.com/zanata/zanata-common/blob/f4345caf9575d55a8737be7d61ddb5d50c8675d7/zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryPoWriter.java#L39)):*
> ```Java
>      * {@link GlossaryEntry#srcLang} and translation term will be used
>      * as comments.
>      */
> ```

Same here. Should just use @see to reference the other method

---

*[zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryPoWriter.java, line 103 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-common/27#-KJYnoa3NmJlYvW5YfcB:-KJYnoa3NmJlYvW5YfcC:306316657) ([raw file](https://github.com/zanata/zanata-common/blob/f4345caf9575d55a8737be7d61ddb5d50c8675d7/zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryPoWriter.java#L103)):*
> ```Java
>     }
> 
>     private void addCommentIfNotEmpty(Message message, String comment) {
> ```

minor thing. Looks like this method can be static

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-common/27)*

**Comment by huangp** [comment]
:lgtm:

<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> #### feat\(glossary export\): Glossary writer
> 
> https://zanata.atlassian.net/browse/ZNTA-153
> 
> 
> 
> https://github.com/zanata/zanata-api/pull/54
> 
> https://github.com/zanata/zanata-client/pull/117
> 
> https://github.com/zanata/zanata-server/pull/1190
> 
> 
> 
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-common/27#-:-KJn9l5SmPO7AhirLaVQ:1417088721)*

**Comment by aeng** [comment]
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryCSVWriter.java, line 45 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-common/27#-KJYlVhO59Fl9_S3xKy_:-KKjqG8kEpUhhif8DUWk:-499146009) ([raw file](https://github.com/zanata/zanata-common/blob/f4345caf9575d55a8737be7d61ddb5d50c8675d7/zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryCSVWriter.java#L45)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> The comment is exactly the same as below. Could just do a @see to reference to the other method. This will avoid us maintaining two copies of text
</details>
Done.

---

*[zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryCSVWriter.java, line 92 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-common/27#-KJYmQho2k33gL35I5uy:-KKjqQzFXTHisRmOzlVi:-499146009) ([raw file](https://github.com/zanata/zanata-common/blob/f4345caf9575d55a8737be7d61ddb5d50c8675d7/zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryCSVWriter.java#L92)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> I don't think you need to use index here when adding to rowx. You are adding srcTerm.getContent() as first element. Then iterate over transLocales for translation terms. Then pos and description. There won't be any missing column in the process (from what I can see. Correct me if I am wrong)
</details>
Done.

---

*[zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryPoWriter.java, line 39 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-common/27#-KJYnWxvkhEZz4dFLulV:-KKjqr_-ZGSer49aN_ys:-499146009) ([raw file](https://github.com/zanata/zanata-common/blob/f4345caf9575d55a8737be7d61ddb5d50c8675d7/zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryPoWriter.java#L39)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> Same here. Should just use @see to reference the other method
</details>
Done.

---

*[zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryPoWriter.java, line 103 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-common/27#-KJYnoa3NmJlYvW5YfcB:-KKjqshsG0TwrzZbWxws:-499146009) ([raw file](https://github.com/zanata/zanata-common/blob/f4345caf9575d55a8737be7d61ddb5d50c8675d7/zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryPoWriter.java#L103)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> minor thing. Looks like this method can be static
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-common/27)*

**Comment by djansen-redhat** [comment]
:white_check_mark: tested

**Pull request merged**
